steps:
  - name: 'grc.io/cloud-bluider/dockers'
    args: ['build','-t','jp/docker-exemplo:latest', '-t', 'jp/docker-exemplo:$SHORT_SHA','.']

  - name: 'docker'
    args: ['run','-d','--name','goapp','jp/docker-exemplo:latest']

  - name: 'docker'
    args: ['exec','goapp','go','test']


#  - name: 'docker'
#    args: ['push','jp/docker-exemplo:latest']
#
#  - name: 'docker'
#    args: ['push','jp/docker-exemplo:$SHORT_SHA']